# Generated by Django 4.0.4 on 2022-05-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviname', models.CharField(max_length=100)),
                ('aviprofession', models.CharField(max_length=100)),
                ('aviage', models.IntegerField()),
            ],
            options={
                'db_table': 'Avitable',
            },
        ),
    ]
