# Generated by Django 4.0.4 on 2022-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
