# Generated by Django 4.0.4 on 2022-06-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0004_textbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('discriptions', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
    ]
