# Generated by Django 4.0.4 on 2022-06-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0005_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='discriptions',
            new_name='description',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
