# Generated by Django 4.0.4 on 2022-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0006_rename_discriptions_quiz_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
