# Generated by Django 4.0.4 on 2022-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0010_question_quiz_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
