# Generated by Django 4.0.4 on 2022-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0012_datastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('tempreture', models.IntegerField()),
                ('feel', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('wind_speed', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
