# Generated by Django 4.0.4 on 2022-07-16 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0013_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feel',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tempreture',
            field=models.FloatField(),
        ),
    ]
