# Generated by Django 4.0.4 on 2022-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0014_weather_time_alter_weather_feel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.IntegerField(),
        ),
    ]
