# Generated by Django 4.0.4 on 2022-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapps', '0015_alter_weather_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
